root = "."

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./src"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "dist", ".git", ".github", "coverage"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_test.go$", ".*.swp$", ".*.swo$"]
  exclude_unchanged = true
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
  include_file = []
  kill_delay = "0.5s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 300
  send_interrupt = true
  stop_on_error = true

[color]
  app = "cyan"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
  error = "red"

[log]
  main_only = true
  silent = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
