package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"app/graph/model"
	"context"
)

// CreatePost is the resolver for the createPost field.
//
//	{
//		"query":"mutation ($input: createPostInput!) {
//		  createPost (input: $input) {
//		    name
//		  }
//		}",
//		"variables":{
//		  "input":{
//		    "name":"Test Post Request Method Route",
//		    "content":"This is a placeholder."
//		  }
//		}
//	}
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	// panic(fmt.Errorf("not implemented: CreatePost - createPost"))
	return &model.Post{}, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	// panic(fmt.Errorf("not implemented: Posts - posts"))
	return []*model.Post{}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
