name: Deploy with docker

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build and store Docker image]
    branches: [main]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io'}}
  APP_NAME: ${{ vars.APP_NAME || github.event.repository.name }}
  APP_PORT: ${{ vars.APP_PORT || 3000 }}
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  pull-and-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: read
      contents: read
      actions: read
      id-token: write

    steps:
      - name: Pull and run Docker image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            echo "::group::Docker Deployment"

            # 登录到容器注册表
            if ! docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USER || github.actor }} -p ${{ secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}; then
              echo "::error::Failed to login to container registry"
              exit 1
            fi

            # 拉取最新镜像
            if ! docker pull ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest; then
              echo "::error::Failed to pull image"
              exit 1
            fi

            # 停止并移除旧容器
            if [ $(docker ps -aq --filter name=${{ env.APP_NAME }}) ]; then
              echo "Stopping and removing existing container..."
              docker stop ${{ env.APP_NAME }}
              docker rm ${{ env.APP_NAME }}
            fi

            docker run --name ${{ env.APP_NAME }} -p ${{ env.APP_PORT }}:3000 -d --restart always ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}

            if [ $(docker images -q --filter dangling=true name=${{ env.APP_NAME }}) ]; then
              docker rmi $(docker images -q --filter dangling=true name=${{ env.APP_NAME }})
            fi

            # 清理未使用的镜像
            echo "Cleaning up unused images..."
            docker image prune -f --filter "until=24h"

            echo "::endgroup::"
